version: '2'

##########################
# Services
##########################
services:
  # app conf container
  data:
    image: tianon/true
    container_name: data
    volumes:
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh

  # nginx container
  nginx:
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    links:
      - php56
      - php70
      - php71
      - mysql
      - es
      - redis
      - ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes_from:
      - ssh-agent
      - data

  # MySQL container
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      # the datavolume persist as long as you are not typing docker-compose down -v
      - datavolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes_from:
      - ssh-agent
      - data

  # PHP 5.6 container
  php56:
    build: ./php/php56/
    expose:
      - 9000
    links:
      - mysql
      - es
      - redis
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes_from:
      - ssh-agent
      - data

  # PHP 7.0 container
  php70:
    build: ./php/php70/
    expose:
      - 9000
    links:
      - mysql
      - es
      - redis
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes_from:
      - ssh-agent
      - data

  # PHP 7.1 container
  php71:
    build: ./php/php71/
    expose:
      - 9000
    links:
      - mysql
      - es
      - redis
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes_from:
      - ssh-agent
      - data

  # Elasticsearch container
  es:
    image: ddogs/elasticsearch
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes_from:
      - ssh-agent
      - data

  # Redis container
  redis:
    image: redis
    ports:
      - "6379"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes_from:
      - ssh-agent
      - data

  # SSH-Agent container
  ssh-agent:
    image: whilp/ssh-agent:latest
    volumes_from:
      - data

##########################
# Volumes
##########################
volumes:
  datavolume: