nginx:
  build: ./nginx/
  ports:
    - 22:22
    - 80:80
    - 443:443
  links:
    - php56
    - php70
    - php71
    - mysql
    - es
    - redis
    - ssh-agent
  volumes:
    - ~/work:/var/www/html
  environment:
    # make ssh keys available via ssh forwarding (see volume entry)
    - SSH_AUTH_SOCK=/ssh-agent/socket
  volumes_from:
    # Use configured whilp/ssh-agent long running container for keys
    - ssh-agent

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: dev
    MYSQL_DATABASE: dev
    MYSQL_USER: dev
    MYSQL_PASSWORD: dev
  environment:
    # make ssh keys available via ssh forwarding (see volume entry)
    - SSH_AUTH_SOCK=/ssh-agent/socket
  volumes_from:
    # Use configured whilp/ssh-agent long running container for keys
    - ssh-agent

php56:
  build: ./php/php56/
  expose:
    - 9000
  links:
    - mysql
    - es
    - redis
  volumes:
    - ~/work:/var/www/html
  environment:
    # make ssh keys available via ssh forwarding (see volume entry)
    - SSH_AUTH_SOCK=/ssh-agent/socket
  volumes_from:
    # Use configured whilp/ssh-agent long running container for keys
    - ssh-agent

php70:
  build: ./php/php70/
  expose:
    - 9000
  links:
    - mysql
    - es
    - redis
  volumes:
    - ~/work:/var/www/html
  environment:
    # make ssh keys available via ssh forwarding (see volume entry)
    - SSH_AUTH_SOCK=/ssh-agent/socket
  volumes_from:
    # Use configured whilp/ssh-agent long running container for keys
    - ssh-agent

php71:
  build: ./php/php71/
  expose:
    - 9000
  links:
    - mysql
    - es
    - redis
  volumes:
    - ~/work:/var/www/html
  environment:
    # make ssh keys available via ssh forwarding (see volume entry)
    - SSH_AUTH_SOCK=/ssh-agent/socket
  volumes_from:
    # Use configured whilp/ssh-agent long running container for keys
    - ssh-agent

es:
  image: ddogs/elasticsearch
  ports:
    - "9200:9200"
  environment:
    # make ssh keys available via ssh forwarding (see volume entry)
    - SSH_AUTH_SOCK=/ssh-agent/socket
  volumes_from:
    # Use configured whilp/ssh-agent long running container for keys
    - ssh-agent

redis:
  image: redis
  ports:
    - "6379"
  environment:
    # make ssh keys available via ssh forwarding (see volume entry)
    - SSH_AUTH_SOCK=/ssh-agent/socket
  volumes_from:
    # Use configured whilp/ssh-agent long running container for keys
    - ssh-agent

ssh-agent:
  image: whilp/ssh-agent:latest
  volumes:
    - ~/.ssh:/root/.ssh