nginx:
  build: ./nginx/
  ports:
    - 80:80
  links:
    - php56
    - php70
    - php71
  volumes:
    - ~/work/vagrant/vHosts:/var/www/html

php56:
  image: php:5.6-fpm
  expose:
    - 9000
  volumes:
    - ~/work/vagrant/vHosts:/var/www/html

php70:
  image: php:7.0-fpm
  expose:
    - 9000
  volumes:
    - ~/work/vagrant/vHosts:/var/www/html

php71:
  image: php:7.1-fpm
  expose:
    - 9000
  volumes:
    - ~/work/vagrant/vHosts:/var/www/html