version: '2'

##########################
# Services
##########################
services:
  # nginx container
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    links:
      - php56
      - php70
      - php71
      - mysql
      - es
      - redis
      - mail
      - shell
      - ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes:
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh

  # MySQL container
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      # the datavolume persist as long as you are not typing docker-compose down -v
      - datavolume:/var/lib/mysql
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - SSH_AUTH_SOCK=/ssh-agent/socket
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  # PHP 5.6 container
  php56:
    build: ./php/php56/
    expose:
      - 9000
    links:
      - mysql
      - es
      - redis
      - mail
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes:
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh

  # PHP 7.0 container
  php70:
    build: ./php/php70/
    expose:
      - 9000
    links:
      - mysql
      - es
      - redis
      - mail
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes:
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh

  # PHP 7.1 container
  php71:
    build: ./php/php71/
    expose:
      - 9000
    links:
      - mysql
      - es
      - redis
      - mail
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes:
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh

  # Elasticsearch container
  es:
    build: ./elasticsearch
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes:
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh

  mail:
    image: mailhog/mailhog:latest

  # Redis container
  redis:
    image: redis
    ports:
      - "6379"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/socket
    volumes:
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh

  shell:
    image: sspreitzer/shellinabox:latest
    environment:
      - SIAB_SSL=false
      - SIAB_USER=dev
      - SIAB_PASSWORD=dev
      - SIAB_SUDO=true
    expose:
      - 4200
    volumes:
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh

  # SSH-Agent container
  ssh-agent:
    image: whilp/ssh-agent:latest
    volumes:
      - ~/work:/var/www/html
      - ~/.ssh:/root/.ssh

##########################
# Volumes
##########################
volumes:
  datavolume:
